### ISSUE TITLE
JOSS review issue2

### ISSUE THREAD

**Issue by catstats** [ckdckd145/statmanager-kr#13]
I've been exploring your package and appreciate its capabilities. However, I encountered a couple of issues that I would like to bring to your attention:

1. The use of index_col="name" as suggested in the Quickstart guide does not work with the provided testdata/testdf.csv. It functions correctly when I switch to another variable, such as "id".

2. The bar plot generated by the command sm.progress(method='ttest_ind', vars='age', group_vars='sex').figure() appears misaligned. Is there a specific version of the plotting library that I should be using to ensure proper alignment?

<img width="914" alt="Screenshot 2024-04-30 at 4 16 56 PM" src="https://github.com/ckdckd145/statmanager-kr/assets/16614051/10547d30-42fc-4c64-ac77-e89d99d465fe">

**Comment by ckdckd145** [comment]
@catstats 

Hi! Thank you again for reviewing statmanager-kr. 

On point 1, I've fixed the readme file in dev branch. Please check [this commit](https://github.com/ckdckd145/statmanager-kr/commit/2288fc123041a6f8e1d2501ea29c0954e4a45e7b).

And, on point 2, after several tests, it seems that if the version of the `seaborn` library is <b>lower than `0.13.0`</b> (e.g. 0.12.2), a misalignment error occurs. I wasn't aware of this, so thanks for bringing it to my attention and I'll make sure to include it in the official documentation. 

Thank you!

**Comment by catstats** [comment]
@ckdckd145
Thank you for your reply.
The README file looks great now, and the misalignment issue in the plot has been resolved after updating Seaborn. I appreciate your thorough testing and prompt updates.
